### ISSUE TITLE
Upterm is deprecated

### ISSUE THREAD

**Issue by achikin** [cdleon/awesome-terminals#1]
According to it's repo README https://github.com/railsware/upterm is deprecated. Could be a good idea to mention that in a list.

**Comment by cdleon** [comment]
Thanks! @achikin I added deprecated to it. But you mean adding like a deprecated list?

**Comment by achikin** [comment]
@cdleon Thank you! I meant exactly what you did :) Btw, there is another Upterm mention in the list inside the MacOS section.

**Comment by cdleon** [comment]
Done. thanks! Closing issue 🙂
