### ISSUE TITLE
EDEX-UI is archived so It wouldn't be wise to recommend it.

### ISSUE THREAD

**Issue by AligatorRicardo** [cdleon/awesome-terminals#26]
EDEX-Ui was first, never mean't to be a serious terminal but it still is awesome. However, the main dev archived the project in 2021 so we can assume that it is dead. It would be a wiser idea to just mark it as "legacy" or depracated or remove it from the list.
Either way, it's your list but please consider this.

**Comment by cdleon** [comment]
thanks! will add as DEPRECATED
